export const BG_CONTAINER = "BG_CONTAINER";
export const INSTANCE_CONTAINER = "INSTANCE_CONTAINER";
export const UI_CONTAINER = "UI_CONTAINER";
export const GAME_CONTAINER = "GAME_CONTAINER";
export const REEL_CONTAINER = "REEL_CONTAINER";
